<a href="https://colab.research.google.com/github/justice-7/Data-Analysis-Programming/blob/main/DAP_Project(202012770_%EB%B0%95%EC%A0%95%EC%9D%98).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 주식 정보 크롤링
참고:
https://blog.naver.com/PostView.nhn?isHttpsRedirect=true&blogId=ym7596&logNo=222056342589&categoryNo=0&parentCategoryNo=0&viewDate=&currentPage=1&postListTopCurrentPage=1&from=postView

In [ ]:
!pip install selenium
!pip install html_table_parse
!pip install pandas
!pip install beutifulsoup4 
!pip install --upgrade beautifulsoup4
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

In [87]:
from bs4 import BeautifulSoup
from selenium import webdriver

import pandas as pd
import time
import xlwt

import numpy as np  
import glob  
import sys
import os

from selenium.webdriver.support.ui import Select

options = webdriver.ChromeOptions()
options.add_argument('--headless')       
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('chromedriver', options=options)

def get_items(prod_items):
    prod_data = []
    for prod_item in prod_items:
        if len(prod_item) <= 1:
            continue
    
        try:
            name = prod_item.select('td')[1].text.strip()
        except:
            name = ''
        try:
            price = prod_item.select('td')[2].text.strip()
        except:
            price = '0'
        try:
             georae= prod_item.select('td')[6].text.strip()
        except:
            georae = '0'
        try:
            stockCnt = prod_item.select('td')[7].text.strip()
        except:
            stockCnt = '0'
        try:
            eps = prod_item.select('td')[8].text.strip()
        except:
            eps = '0'
        try:
            per = prod_item.select('td')[9].text.strip()
        except:
            per = '0'
        try:
            roe = prod_item.select('td')[10].text.strip()
        except:
            roe = '0'
        try:
            pbr = prod_item.select('td')[11].text.strip()
        except:
            pbr = '0'
        
   
        prod_data.append([name,price,georae,stockCnt,eps,per,roe,pbr])
    return prod_data

[os.remove(f) for f in glob.glob("./stock*.csv")] # 만들어진 파일 삭제(stock*.csv)

for i in range(1,7):
    url='https://finance.naver.com/sise/sise_market_sum.naver?&page='+str(i)
    driver.get(url)
    time.sleep(2)

    if(i==1):
        #원하는 항목을 체크 후 적용하기 클릭
        driver.find_element_by_id('option4').click()
        driver.find_element_by_id('option15').click()
        driver.find_element_by_id('option23').click()
        driver.find_element_by_id('option24').click()
        driver.find_element_by_xpath('/html/body/div[3]/div[2]/div[2]/div[1]/div[2]/form/div/div/div/a[1]/img').click()

    time.sleep(2)

    html = driver.page_source
    soup = BeautifulSoup(html,'html.parser')

    prod_items = soup.select('table.type_2 > tbody > tr')

    prod_data_fin = get_items(prod_items)

    data = pd.DataFrame(prod_data_fin)

    data.columns = ['이름','현재가','거래량','상장주식수','주당순이익','PER','ROE','PBR']

    data.to_csv('./stock'+str(i)+'.csv')

    time.sleep(2)

all_data = []  
for f in glob.glob('./stock*.csv'): # stock으로 시작하는 파일  
    df = pd.read_csv(f)  
    all_data.append(df)

dataCombine = pd.concat(all_data, axis=0, ignore_index=True)
# 파일저장 
dataCombine.to_csv("./stock.csv", index=False)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:73: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:74: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:75: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:76: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:77: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead

In [88]:
df=pd.read_csv('./stock.csv')
df=df[['이름','현재가','거래량','상장주식수','주당순이익','PER','ROE','PBR']]
df

             이름      현재가         거래량   상장주식수   주당순이익       PER    ROE   PBR
0    KODEX 단기채권  102,990      45,051  18,871     NaN       NaN    NaN   NaN
1            효성   91,100      52,066  21,071  18,374      4.96  -2.26  0.71
2    KODEX 레버리지   21,555  15,523,157  83,600     NaN       NaN    NaN   NaN
3          신풍제약   33,600   2,473,385  52,985       6  5,600.00   1.72  4.71
4            대웅   30,450      67,208  58,142   1,816     16.77   15.1  1.81
..          ...      ...         ...     ...     ...       ...    ...   ...
295       하이트진로   29,550     180,398  70,134     734     40.26   8.23  1.89
296        현대해상   23,100     426,131  89,400   4,320      5.35   7.13  0.39
297      롯데정밀화학   78,700      93,959  25,800  16,517      4.76  12.65  1.02
298       코오롱인더   71,300     180,690  27,519   6,443     11.07    9.7  0.88
299        현대위아   72,100     177,370  27,195   1,342     53.73   1.96  0.59

[300 rows x 8 columns]